### ISSUE TITLE
Git push fails fs.js:557

### ISSUE THREAD

**Issue by exmex** [naholyr/github-todos#30]
```
fs.js:557
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^
Error: ENOENT: no such file or directory, open 'C:\dev\tty'
at Object.fs.openSync (fs.js:557:18)
at Object.<anonymous> (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\github-todos\node_modules\ttys\index.js:9:18)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
at Function.Module._load (module.js:441:3)
at Module.require (module.js:500:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\github-todos\index.js:6:12)
```

**Comment by nayrrod** [comment]
Same here

**Comment by SanchoBlaze** [comment]
Same for me

**Comment by atasak** [comment]
Same here. @naholyr do you support Windows? Because if you try to open /dev/tty it will only work on Unix systems...
