### ISSUE TITLE
Unhandled rejection ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by ghost** [naholyr/github-todos#33]
Using node v13.6.0 (64-bit) on Windows 10.

When I run `github-todos init` command, I receive this error:

```
Unhandled rejection ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\joaos\AppData\Roaming\npm\node_modules\github-todos\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\joaos\AppData\Roaming\npm\node_modules\github-todos\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\joaos\AppData\Roaming\npm\node_modules\github-todos\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\joaos\AppData\Roaming\npm\node_modules\github-todos\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
```

**Comment by adi-g15** [comment]
Have you found the cause? I am had the same problem, couldn't even try it.

**Comment by ghost** [comment]
> Have you found the cause? I am had the same problem, couldn't even try it.

Unfortunately, no.
